[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sys_monitor"
version = "0.0.1"
authors = [
  { name="Ravi Nain", email="ravinain100@gmail.com" },
]
description = "To get system details easily using python - Currently available for linux only"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/qaravinain/sys-monitor"
"Bug Tracker" = "https://github.com/qaravinain/sys-monitor/issues"